
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:11 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.17.0-1020-azure - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCCompilerFlag.cmake:56 (cmake_check_compiler_flag)"
      - "build-web/_deps/raylib-src/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "build-web/_deps/raylib-src/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "build-web/_deps/raylib-src/CMakeLists.txt:26 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-twMuwC"
      binary: "/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-twMuwC"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: " -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: " --preload-file \"/home/runner/work/supermeowmeow/supermeowmeow/assets@/assets\" --shell-file \"/home/runner/work/supermeowmeow/supermeowmeow/shell.html\""
      CMAKE_MODULE_PATH: "/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/supermeowmeow/supermeowmeow/build-web/_deps/raylib-src/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-twMuwC'
        
        Run Build Command(s): /usr/local/bin/ninja -v cmTC_cfce9
        [1/2] /home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/emcc -DCOMPILER_HAS_THOSE_TOGGLES  -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1  -std=gnu99   -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_cfce9.dir/src.c.o -MF CMakeFiles/cmTC_cfce9.dir/src.c.o.d -o CMakeFiles/cmTC_cfce9.dir/src.c.o -c /home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-twMuwC/src.c
        shared:INFO: (Emscripten: Running sanity checks)
        emcc: warning: linker setting ignored during compilation: 'USE_GLFW' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ASSERTIONS' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'WASM' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ASYNCIFY' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'INITIAL_MEMORY' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ALLOW_MEMORY_GROWTH' [-Wunused-command-line-argument]
        [2/2] : && /home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/emcc -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1 --preload-file "/home/runner/work/supermeowmeow/supermeowmeow/assets@/assets" --shell-file "/home/runner/work/supermeowmeow/supermeowmeow/shell.html" CMakeFiles/cmTC_cfce9.dir/src.c.o -o cmTC_cfce9.js   && :
        cache:INFO: generating system asset: symbol_lists/2207466fb5df827a1fac92bd6bbe0b697fd515c3.json... (this will be cached in "/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cache/symbol_lists/2207466fb5df827a1fac92bd6bbe0b697fd515c3.json" for subsequent builds)
        cache:INFO:  - ok
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "build-web/_deps/raylib-src/cmake/LibraryConfigurations.cmake:21 (check_c_source_compiles)"
      - "build-web/_deps/raylib-src/cmake/LibraryConfigurations.cmake:265 (raylib_check_libatomic_required)"
      - "build-web/_deps/raylib-src/src/CMakeLists.txt:57 (include)"
    checks:
      - "Performing Test RAYLIB_ATOMICS_WITHOUT_LIBATOMIC"
    directories:
      source: "/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-C8kcZL"
      binary: "/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-C8kcZL"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: "-fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: " --preload-file \"/home/runner/work/supermeowmeow/supermeowmeow/assets@/assets\" --shell-file \"/home/runner/work/supermeowmeow/supermeowmeow/shell.html\""
      CMAKE_MODULE_PATH: "/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/cmake/Modules;/home/runner/work/supermeowmeow/supermeowmeow/build-web/_deps/raylib-src/cmake"
    buildResult:
      variable: "RAYLIB_ATOMICS_WITHOUT_LIBATOMIC"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-C8kcZL'
        
        Run Build Command(s): /usr/local/bin/ninja -v cmTC_256ce
        [1/2] /home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/emcc -DRAYLIB_ATOMICS_WITHOUT_LIBATOMIC  -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1  -std=gnu99 -MD -MT CMakeFiles/cmTC_256ce.dir/src.c.o -MF CMakeFiles/cmTC_256ce.dir/src.c.o.d -o CMakeFiles/cmTC_256ce.dir/src.c.o -c /home/runner/work/supermeowmeow/supermeowmeow/build-web/CMakeFiles/CMakeScratch/TryCompile-C8kcZL/src.c
        emcc: warning: linker setting ignored during compilation: 'USE_GLFW' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ASSERTIONS' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'WASM' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ASYNCIFY' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'INITIAL_MEMORY' [-Wunused-command-line-argument]
        emcc: warning: linker setting ignored during compilation: 'ALLOW_MEMORY_GROWTH' [-Wunused-command-line-argument]
        [2/2] : && /home/runner/work/_temp/4c97398e-9e9b-4397-958b-3908d623bacf/emsdk-main/upstream/emscripten/emcc -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY -s INITIAL_MEMORY=64MB -s ALLOW_MEMORY_GROWTH=1 --preload-file "/home/runner/work/supermeowmeow/supermeowmeow/assets@/assets" --shell-file "/home/runner/work/supermeowmeow/supermeowmeow/shell.html" CMakeFiles/cmTC_256ce.dir/src.c.o -o cmTC_256ce.js   && :
        
      exitCode: 0
...
