name: Build Web

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: latest
        actions-cache-folder: 'emsdk-cache'
      
    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build
      
    - name: Create Build Directory
      run: mkdir -p build-web
      
    - name: Configure CMake
      run: |
        cd build-web
        emcmake cmake -DPLATFORM_WEB=ON -DCMAKE_BUILD_TYPE=Release -DEXECUTABLE_NAME=index -G Ninja ..
        
    - name: Build
      run: |
        cd build-web
        cmake --build . --config Release
        
    - name: Upload Web Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: |
          build-web/index.html
          build-web/index.js
          build-web/index.wasm
          build-web/index.data
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build-web
        branch: gh-pages 